# Generated by Django 4.0.1 on 2022-01-05 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musci',
            new_name='Music',
        ),
    ]
