# Generated by Django 4.0.1 on 2022-01-06 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_rename_musci_music'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music',
        ),
    ]
