# Generated by Django 4.0.1 on 2022-01-08 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0006_music'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music',
        ),
    ]
