# Generated by Django 4.0.1 on 2022-01-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0008_musical'),
    ]

    operations = [
        migrations.AddField(
            model_name='musical',
            name='audio_file',
            field=models.FileField(null=True, upload_to='spots'),
        ),
        migrations.AddField(
            model_name='musical',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='spots_image'),
        ),
        migrations.AddField(
            model_name='musical',
            name='time_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='musical',
            name='artist',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='musical',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
